# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: word_game.proto
# Generated protocol buffer code.
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
    name='word_game.proto',
    package='word_game',
    syntax='proto3',
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x0fword_game.proto\x12\tword_game\"\x07\n\x05\x45empty\"\x1a\n\x07Pangram'
                  b'\x12\x0f\n\x07pangram\x18\x01 \x01(\t\"\x14\n\x04Word\x12\x0c\n\x04word\x18\x01 \x01(\t\"4\n'
                  b'\x05Score'
                  b'\x12\x0b\n\x03msg\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x05\x12\x0f\n\x07pangram'
                  b'\x18\x03 \x01(\t2j\n\x08WordGame\x12.\n\x04ping\x12\x10.word_game.Empty\x1a\x12.word_game.Pangram'
                  b'\"\x00\x12.\n\x07getWord\x12\x0f.word_game.Word\x1a\x10.word_game.Score\"\x00\x62\x06proto3'
)

_EMPTY = _descriptor.Descriptor(
    name='Empty',
    full_name='word_game.Empty',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=30,
    serialized_end=37,
)

_PANGRAM = _descriptor.Descriptor(
    name='Pangram',
    full_name='word_game.Pangram',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='pangram', full_name='word_game.Pangram.pangram', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=39,
    serialized_end=65,
)

_WORD = _descriptor.Descriptor(
    name='Word',
    full_name='word_game.Word',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='word', full_name='word_game.Word.word', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=67,
    serialized_end=87,
)

_SCORE = _descriptor.Descriptor(
    name='Score',
    full_name='word_game.Score',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='msg', full_name='word_game.Score.msg', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='score', full_name='word_game.Score.score', index=1,
            number=2, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='pangram', full_name='word_game.Score.pangram', index=2,
            number=3, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=89,
    serialized_end=141,
)

DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['Pangram'] = _PANGRAM
DESCRIPTOR.message_types_by_name['Word'] = _WORD
DESCRIPTOR.message_types_by_name['Score'] = _SCORE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
    'DESCRIPTOR': _EMPTY,
    '__module__': 'word_game_pb2'
    # @@protoc_insertion_point(class_scope:word_game.Empty)
})
_sym_db.RegisterMessage(Empty)

Pangram = _reflection.GeneratedProtocolMessageType('Pangram', (_message.Message,), {
    'DESCRIPTOR': _PANGRAM,
    '__module__': 'word_game_pb2'
    # @@protoc_insertion_point(class_scope:word_game.Pangram)
})
_sym_db.RegisterMessage(Pangram)

Word = _reflection.GeneratedProtocolMessageType('Word', (_message.Message,), {
    'DESCRIPTOR': _WORD,
    '__module__': 'word_game_pb2'
    # @@protoc_insertion_point(class_scope:word_game.Word)
})
_sym_db.RegisterMessage(Word)

Score = _reflection.GeneratedProtocolMessageType('Score', (_message.Message,), {
    'DESCRIPTOR': _SCORE,
    '__module__': 'word_game_pb2'
    # @@protoc_insertion_point(class_scope:word_game.Score)
})
_sym_db.RegisterMessage(Score)

_WORDGAME = _descriptor.ServiceDescriptor(
    name='WordGame',
    full_name='word_game.WordGame',
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=143,
    serialized_end=249,
    methods=[
        _descriptor.MethodDescriptor(
            name='ping',
            full_name='word_game.WordGame.ping',
            index=0,
            containing_service=None,
            input_type=_EMPTY,
            output_type=_PANGRAM,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name='getWord',
            full_name='word_game.WordGame.getWord',
            index=1,
            containing_service=None,
            input_type=_WORD,
            output_type=_SCORE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
    ])
_sym_db.RegisterServiceDescriptor(_WORDGAME)

DESCRIPTOR.services_by_name['WordGame'] = _WORDGAME

# @@protoc_insertion_point(module_scope)
