# Generated by the gRPC Python protocol compiler plugin.
# Client and server classes corresponding to protobuf-defined services.
import grpc

import word_game_pb2 as word__game__pb2


class WordGameStub(object):
    # Missing associated documentation comment in .proto file.

    def __init__(self, channel):
        # Constructor.

        # Args:
        # channel: A grpc.Channel.

        self.ping = channel.unary_unary(
            '/word_game.WordGame/ping',
            request_serializer=word__game__pb2.Empty.SerializeToString,
            response_deserializer=word__game__pb2.Pangram.FromString,
        )
        self.getWord = channel.unary_unary(
            '/word_game.WordGame/getWord',
            request_serializer=word__game__pb2.Word.SerializeToString,
            response_deserializer=word__game__pb2.Score.FromString,
        )


class WordGameServicer(object):
    # Missing associated documentation comment in .proto file.

    def ping(self, request, context):
        # Missing associated documentation comment in .proto file.
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getWord(self, request, context):
        # Missing associated documentation comment in .proto file.
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WordGameServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'ping': grpc.unary_unary_rpc_method_handler(
            servicer.ping,
            request_deserializer=word__game__pb2.Empty.FromString,
            response_serializer=word__game__pb2.Pangram.SerializeToString,
        ),
        'getWord': grpc.unary_unary_rpc_method_handler(
            servicer.getWord,
            request_deserializer=word__game__pb2.Word.FromString,
            response_serializer=word__game__pb2.Score.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'word_game.WordGame', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class WordGame(object):
    # Missing associated documentation comment in .proto file.

    @staticmethod
    def ping(request,
             target,
             options=(),
             channel_credentials=None,
             call_credentials=None,
             insecure=False,
             compression=None,
             wait_for_ready=None,
             timeout=None,
             metadata=None):
        return grpc.experimental.unary_unary(request, target, '/word_game.WordGame/ping',
                                             word__game__pb2.Empty.SerializeToString,
                                             word__game__pb2.Pangram.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getWord(request,
                target,
                options=(),
                channel_credentials=None,
                call_credentials=None,
                insecure=False,
                compression=None,
                wait_for_ready=None,
                timeout=None,
                metadata=None):
        return grpc.experimental.unary_unary(request, target, '/word_game.WordGame/getWord',
                                             word__game__pb2.Word.SerializeToString,
                                             word__game__pb2.Score.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
